EDIR=/data/local/env.d/
if [ $(id -u) -eq 0 ] ;
then
        if [ -f $EDIR/bashrc.root ] ;
        then
        . $EDIR/bashrc.root
        fi
else
        if [ -f $EDIR/bashrc.user ] ;
        then
        . $EDIR/bashrc.user
        fi
fi

